a = input("Enter 1st number : ")
b = input("Enter 2nd number : ")
print("\n")
print("Addition       : ",int(a)+int(b))
print("subtraction    : ",int(a)-int(b))
print("multiplication : ",int(a)*int(b))
print("division       : ",int(a)/int(b))
print("modulus        : ",int(a)%int(b))
print("double division: ",int(a)//int(b))
